declare const fs: any;
declare const vm: any;
declare const customRequireResolve: any;
declare const tscFileName: any;
declare var typescriptFilename: any;
declare let content: any;
declare const script: any;
declare const context: any;
declare const ts: any;
